version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  
    env_file:
      - ./backend/.env
    restart: unless-stopped

  ml-api:
    build:
      context: ./flaskAPI
      dockerfile: Dockerfile
    ports:
      - "5001:5001" 
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: unless-stopped
